// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
 
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2W0lFaUa_brICFDdYOJR9HF7Z6tMRh8',
    appId: '1:745813035451:web:90970b0c1830326cce9c9e',
    messagingSenderId: '745813035451',
    projectId: 'lake-water-level-widget-app',
    authDomain: 'lake-water-level-widget-app.firebaseapp.com',
    storageBucket: 'lake-water-level-widget-app.appspot.com',
    measurementId: 'G-08946CN66D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmEKoSzmF77dZi7bfJFmoEa0brnIEnuxk',
    appId: '1:745813035451:android:3476b4336c2f736cce9c9e',
    messagingSenderId: '745813035451',
    projectId: 'lake-water-level-widget-app',
    storageBucket: 'lake-water-level-widget-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHVMgxdWNP6LU-UtmmXRo8o5f08TVEbCQ',
    appId: '1:745813035451:ios:37f4993160a191a9ce9c9e',
    messagingSenderId: '745813035451',
    projectId: 'lake-water-level-widget-app',
    storageBucket: 'lake-water-level-widget-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHVMgxdWNP6LU-UtmmXRo8o5f08TVEbCQ',
    appId: '1:745813035451:ios:37f4993160a191a9ce9c9e',
    messagingSenderId: '745813035451',
    projectId: 'lake-water-level-widget-app',
    storageBucket: 'lake-water-level-widget-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI2W0lFaUa_brICFDdYOJR9HF7Z6tMRh8',
    appId: '1:745813035451:web:11f58174afea448fce9c9e',
    messagingSenderId: '745813035451',
    projectId: 'lake-water-level-widget-app',
    authDomain: 'lake-water-level-widget-app.firebaseapp.com',
    storageBucket: 'lake-water-level-widget-app.appspot.com',
    measurementId: 'G-48SXZCM1KD',
  );

}